Update README.md
obitodarky/Reps-Events-Mobile pull request #10
Opened 2019-07-22 15:10 UTC by arps18

Added Flutter installation links and other useful links.

2019-07-23 10:57 UTC, harshil1712 commented
Add a section in the begning where it describes the App

2019-07-23 11:02 UTC, harshil1712 requested changes
Please read the issue properly. The REAMDE file should contain recipe on how to install Flutter, setup the developer environment, and provide some references.  All the other details aren't required.

2019-07-23 11:02 UTC, harshil1712 commented on reps_event_app/README.md
> +## About Flutter
```suggestion
## About Flutter
```
It's okay to not have this section

2019-07-23 11:02 UTC, harshil1712 commented on reps_event_app/README.md
> +### Beautiful apps
```suggestion
### Beautiful apps
```
This section is also not required

2019-08-03 04:46 UTC, obitodarky commented
Closing this since we need the Readme file in the `dev` branch and not in the `master` branch. 
@arps18  please make the changes requested by @harshil1712 and send a PR to the `dev` branch. Thanks

2019-08-03 04:46 UTC, closed without merging