Tabs implemented to replace Drawer
obitodarky/Reps-Events-Mobile pull request #45
Opened 2019-10-04 07:53 UTC by Thesmader

Tabview implemented to replace Drawer.

Fixes #21  

**Summary**: 
Tabs added for Events, People and About screens. Dark mode button added at top right.

**Screenshots for the change**: 

Before: 
![tab_ss](https://user-images.githubusercontent.com/34758667/66190498-c3c77100-e6a9-11e9-8486-c3090d26119c.PNG)

After: 
![drawer_ss](https://user-images.githubusercontent.com/34758667/66190625-13a63800-e6aa-11e9-96c6-aaca21b91223.jpeg)

2019-10-07 15:49 UTC, obitodarky requested changes
@Thesmader this looks good to me. Can you please resolve merge conflicts?

2019-10-07 16:40 UTC, Thesmader commented
Sure. I'll resolve the merge conflicts.

2019-10-09 04:46 UTC, obitodarky approved these changes

2019-10-15 04:50 UTC, AyushBherwani1998 approved these changes

2019-10-15 12:00 UTC, merged